services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data/indexes:/app/data/indexes
    command: python -m pytest tests

  streamlit:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data/indexes:/app/data/indexes
    ports:
      - "8501:8501"
    command: streamlit run src/frontend/app.py --server.address=0.0.0.0
